### ISSUE TITLE
Generierte Kanäle haben als Name eine Zahl

### ISSUE THREAD

**Issue by Omega236** [AWhiteKnight/ioBroker.moma#45]
Der Adapter erzeugt einige Datenpunkte bei denen der Name als Zahl und nicht als String erzeugt wird. Dadurch kann der Adapter Admin nicht mehr nach Namen Sortieren, da der Admin im Client-JS-Code versucht den Namen mit der Funktion toLowerCase() zu bearbeiten. diese Funktion gibt es aber bei einer Zahl nicht und er bricht daraufhin ab.

`{
  "type": "channel",
  "common": {
    "name": 1
  },
  "native": {},
  "from": "system.adapter.moma.3",
  "user": "system.user.admin",
  "ts": 1580751546979,
  "_id": "moma.3.fsSize.1",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`
Adater erstellen und Filesystem aktivieren.
Ebenfalls betroffen:
moma.0.currentLoad.cpus.0
moma.0.currentLoad.cpus.1
moma.0.currentLoad.cpus.2
moma.0.currentLoad.cpus.3
moma.0.fsSize.0

Zusätzliche Informationen:
https://github.com/ioBroker/ioBroker.admin/issues/504

Versionen:
Nodejs: v10.17.0
js-controller: 2.1.1
Admin: 3.7.9
MOMA: 1.2.3

**Comment by AWhiteKnight** [comment]
gelöst mit 1.2.4: Die Namen erhalten ein 'i' vor der Zahl, wenn sie eine reine Zahl sind.
