### ISSUE TITLE
Update stable version in repo from 1.2.3 to 1.2.4

### ISSUE THREAD

**Issue by GermanBluefox** [AWhiteKnight/ioBroker.moma#47]
# Think about update stable version to 1.2.4
**Version**: stable=**1.2.3** (150 days old) => latest=**1.2.4** (15 days old)
**Installs**: stable=**887** (66.49%), latest=**300** (22.49%), total=**1334**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L841)

**Comment by AWhiteKnight** [comment]
done
