### ISSUE TITLE
after updating js-controller 3.x TypeError: adapter.getForeignStateAChangedsync is not a function

### ISSUE THREAD

**Issue by moeff** [AWhiteKnight/ioBroker.moma#49]
After i have upgraded the js-controller 3.x - moma is permanently restarting

js-controller: 3.0.14
moma: 1.2.5

LOG output:

`

moma.0 | 2020-04-22 11:32:17.088 | error | (1382044) TypeError: adapter.getForeignStateAChangedsync is not a function at Interval2.logError (/opt/iobroker/node_modules/iobroker.moma/lib/Interval.js:66:17) at process._tickCallback (inte
-- | -- | -- | --
moma.0 | 2020-04-22 11:32:17.087 | error | (1382044) uncaught exception: adapter.getForeignStateAChangedsync is not a function

`

**Comment by AWhiteKnight** [comment]
fixed in 1.2.6
