### ISSUE TITLE
Update stable version in repo from 1.2.6 to 1.2.7

### ISSUE THREAD

**Issue by GermanBluefox** [AWhiteKnight/ioBroker.moma#50]
# Think about update stable version to 1.2.7
**Version**: stable=**1.2.6** (189 days old) => latest=**1.2.7** (15 days old)
**Installs**: stable=**995** (63.05%), latest=**325** (20.6%), total=**1578**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L931)

**Comment by AWhiteKnight** [comment]
done
