### ISSUE TITLE
State "moma.0.xxx" has no  existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Omega236** [AWhiteKnight/ioBroker.moma#52]
**Describe the bug**  
Erzeugt seit js-controller 3.2.x viele Warn logs weil states mit "raw_x" befüllt werden

**To Reproduce**  
1. Install Adapter
2. Show log
3. Noch mehr logs nach aktivieren von "Aktuelle CPU-Auslastung" (Bei Intervall 0 (Sekunden))

**Screenshots & Logfiles**  
Direkt nach installtion auf Testsystem:

moma.0 | 2021-02-26 20:07:30.678 | warn | (439)  State "moma.0.moma.meta.hosts.IoBrokerTestSystem1.updates" has no  existing object, this might lead to an error in future versions
-- | -- | -- | --
moma.0 | 2021-02-26 20:07:30.669 | warn | (439)  State "moma.0.moma.meta.hosts.IoBrokerTestSystem1.numUpdates" has no  existing object, this might lead to an error in future versions

Auf meinem Produktivsystem

moma.0 | 2021-02-26 20:01:51.310 | warn | (494) State "moma.0.currentLoad.cpus.3.raw_load_idle" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
moma.0 | 2021-02-26 20:01:51.258 | warn | (494) State "moma.0.currentLoad.cpus.3.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:51.207 | warn | (494) State "moma.0.currentLoad.cpus.3.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:51.156 | warn | (494) State "moma.0.currentLoad.cpus.3.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:51.067 | warn | (494) State "moma.0.currentLoad.cpus.2.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:51.015 | warn | (494) State "moma.0.currentLoad.cpus.2.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.967 | warn | (494) State "moma.0.currentLoad.cpus.2.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.916 | warn | (494) State "moma.0.currentLoad.cpus.2.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.831 | warn | (494) State "moma.0.currentLoad.cpus.1.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.782 | warn | (494) State "moma.0.currentLoad.cpus.1.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.734 | warn | (494) State "moma.0.currentLoad.cpus.1.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.681 | warn | (494) State "moma.0.currentLoad.cpus.1.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.518 | warn | (494) State "moma.0.currentLoad.cpus.0.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.470 | warn | (494) State "moma.0.currentLoad.cpus.0.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.422 | warn | (494) State "moma.0.currentLoad.cpus.0.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.369 | warn | (494) State "moma.0.currentLoad.cpus.0.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.287 | warn | (494) State "moma.0.currentLoad.raw_currentload_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.238 | warn | (494) State "moma.0.currentLoad.raw_currentload_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.190 | warn | (494) State "moma.0.currentLoad.raw_currentload_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-26 20:01:50.141 | warn | (494) State "moma.0.currentLoad.raw_currentload" has no existing object, this might lead to an error in future versions

**Versions:**  
 - Adapter version: 1.2.7
 - JS-Controller version: 3.2.16
 - Node version: v12.20.0
 - Operating system: linux (Docker buanet 5.1)

**Additional context**

**Comment by AWhiteKnight** [comment]
Solved in 1.2.8 which is in latest repository
